spring:
  datasource:
    url: jdbc:mysql://114.55.0.204:3306/manager
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: manager
    password: manager
  resources:
    static-locations: classpath:/static/

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

server:
  port: 8081
